### ISSUE TITLE
[OID4VC] Complete presentation definition APIs

### ISSUE THREAD

**Issue by aw-al** [openwallet-foundation/acapy-plugins#1256]
Current OID4VC plugin only implements POST API to create a presentation definition (`/oid4vp/presentation-definition`), there is no method to list and manage the created presentation definitions. 

It would be beneficial to complete the presentation definition APIs with the following endpoints:

- `GET /oid4vp/presentation-definitions`
List all presentation definition records
- `DELETE /oid4vp/presentation-definition/{pres_def_id}`
Delete a presentation definition record by `pres_def_id`
- `GET /oid4vp/presentation-definition/{pres_def_id}`
Show a presentation definition record by `pres_def_id`

**Comment by dbluhm** [comment]
Resolved by #1275
